# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, develop]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: registry
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - run: yarn -v

      - uses: bahmutov/npm-install@v1

      - name: Docker push
        if: ${{ contains(github.ref, 'refs/tags/v') }}
        run: |
          VUE_APP_VERSION=${{ env.GIT_BRANCH_NAME }}-${{ github.sha }} yarn build
          docker build -t ${{ secrets.VUE_IMAGE }}:${{ env.GIT_BRANCH_NAME }} .
          docker push ${{ secrets.VUE_IMAGE }}:${{ env.GIT_BRANCH_NAME }}

      - name: Deploy to prod
        uses: garygrossgarten/github-action-ssh@release
        if: ${{ contains(github.ref, 'refs/tags/v') }}
        with:
          command: kubectl -n hong set image deploy hong-vue hong-vue=${{ secrets.VUE_IMAGE }}:${{ env.GIT_BRANCH_NAME }}
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_PRIVATE_KEY}}

      - name: Docker push test
        if: ${{ contains(github.ref, 'refs/heads/develop') }}
        run: |
          VUE_APP_VERSION=${{ env.GIT_BRANCH_NAME }}-${{ github.sha }} yarn build
          docker build -t ${{ secrets.VUE_IMAGE }}:dev${{ github.run_number }} .
          docker push ${{ secrets.VUE_IMAGE }}:dev${{ github.run_number }}

      - name: Deploy to test
        uses: garygrossgarten/github-action-ssh@release
        if: ${{ contains(github.ref, 'refs/heads/develop') }}
        with:
          command: kubectl -n hong set image deploy test-hong-vue hong-vue=${{ secrets.VUE_IMAGE }}:dev${{ github.run_number }}
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_PRIVATE_KEY}}
